apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-follower
  labels:
    app: redis
    role: follower
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        role: follower
        tier: backend
    spec:
      containers:
      - name: follower
        image: gcr.io/google_samples/gb-redis-follower:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
---
kind: Service
apiVersion: v1
metadata:
  name: redis-follower
  labels:
    app: redis
    role: follower
    tier: backend
spec:
  selector:
    app: redis
    role: follower
    tier: backend
  type: ClusterIP
  ports:
  - port:  6379
    targetPort: 6379