version: '3.8'

services:
  jenkins:
    image: jenkins
    build: .
    container_name: jenkins
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins:/var/jenkins_home
    networks:
      - jenkins

volumes:
  jenkins:
    name: jenkins

networks:
  jenkins:
    name: jenkins
